"""Sync models with database

Revision ID: 1390dd1a1b19
Revises: 31e728447d50
Create Date: 2025-06-04 17:31:07.735113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1390dd1a1b19'
down_revision = '31e728447d50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_business_settings')
    with op.batch_alter_table('business_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('business_address', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('contact_number', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('contact_email', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('business_type', sa.String(length=64), nullable=True))
        batch_op.drop_column('phone')
        batch_op.drop_column('email')
        batch_op.drop_column('name')
        batch_op.drop_column('logo_filename')
        batch_op.drop_column('address')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barcode', sa.String(length=128), nullable=True))
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.create_unique_constraint('uq_product_barcode', ['barcode'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('uq_product_barcode', type_='unique')
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('barcode')

    with op.batch_alter_table('business_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=256), nullable=True))
        batch_op.add_column(sa.Column('logo_filename', sa.VARCHAR(length=256), nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=128), nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_column('business_type')
        batch_op.drop_column('contact_email')
        batch_op.drop_column('contact_number')
        batch_op.drop_column('business_address')
        batch_op.drop_column('business_name')

    op.create_table('_alembic_tmp_business_settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('business_name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('business_address', sa.VARCHAR(length=256), nullable=True),
    sa.Column('contact_number', sa.VARCHAR(length=32), nullable=True),
    sa.Column('contact_email', sa.VARCHAR(length=128), nullable=True),
    sa.Column('business_type', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
