"""Add model_number column to Product

Revision ID: 2b3c4d5e6f7g  # <-- use the new revision ID generated by Alembic
Revises: 1390dd1a1b19
Create Date: 2025-06-04 XX:XX:XX.XXXXXX

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2b3c4d5e6f7g'  # <-- your new revision ID
down_revision = '1390dd1a1b19'
branch_labels = None
depends_on = None

def upgrade():
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_number', sa.String(length=128), nullable=True))

def downgrade():
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('model_number')